---
- name: Assignment_Multiple_shell_command
  hosts: all
  tasks:
  - name: shell_command
    shell: ls
    register: target_ls
    shell: cat /root/a
    register: target_cat
  - debug: 
      var: target_ls.stdout_lines 
      var: target_cat.stdout_lines 
