---
- name: assignment3
  hosts: all
  tasks:
  - name: copying 
    copy: 
      src: /root/add.sh
      dest: /root
  - name: shell_to_execute_script  
    shell: sh /root/add.sh
    register: target_sh
  - debug: 
      var: target_sh.stdout_lines
